import type { Metadata } from "next";
import "./globals.css";
import { ServerAuthProvider } from "@/providers/auth/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <ServerAuthProvider>
          <main className="max-w-[750px] mx-auto">
            {children}
          </main>
        </ServerAuthProvider>
      </body>
    </html>
  );
}
